CREATE DATABASE SENAI;
GO
USE SENAI;
GO
CREATE TABLE CAIXA(
ID_CAIXA			INTEGER  IDENTITY(1,1),
DATA				DATETIME,
SALDO_INICIAL		DECIMAL(10,2),
SALDO_FINAL		DECIMAL(10,2),
);
GO
INSERT INTO CAIXA
VALUES(CONVERT(DATETIME,CONVERT(VARCHAR, GETDATE(),103)),100,100)
GO
CREATE TABLE VENDAS(
ID_VENDAS		INTEGER  IDENTITY(1,1),
DATA				DATETIME,
CODIGO			INT,
VALOR			DECIMAL(10,2)
);
GO
GO
CREATE TRIGGER TGR_VENDAS
ON VENDAS
FOR INSERT
AS
BEGIN
		DECLARE
		@VALOR		DECIMAL(10,2),
		@DATA		DATETIME

		SELECT @DATA = DATA, @VALOR = VALOR FROM INSERTED

		UPDATE CAIXA SET SALDO_FINAL = SALDO_FINAL + @VALOR
		WHERE DATA = @DATA
END
GO
INSERT INTO VENDAS
VALUES(CONVERT(DATETIME,CONVERT(VARCHAR, GETDATE(),103)),1,10)
GO
GO
INSERT INTO VENDAS
VALUES(CONVERT(DATETIME,CONVERT(VARCHAR, GETDATE(),103)),3,40)
GO
 CREATE TRIGGER TGR_VENDAS_DELETE
 ON VENDAS
 FOR DELETE
 AS 
 BEGIN
		DECLARE
		@VALOR		DECIMAL(10,2),
		@DATA		DATETIME

		SELECT @DATA = DATA, @VALOR = VALOR FROM deleted

		UPDATE CAIXA SET SALDO_FINAL = SALDO_FINAL + @VALOR
		WHERE DATA = @DATA
END
SELECT * FROM VENDAS
SELECT * FROM CAIXA
DELETE FROM VENDAS WHERE CODIGO = 1
GO